### ISSUE TITLE
Check identity status during persistent DID login

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-passport#13]
Identities with non-active identity documents are allowed to login because the status of the identity is not being checked here:

https://github.com/digitalbazaar/bedrock-passport/blob/master/lib/passport.js#L332

Proposed solutions:
1. Specify `sysStatus: 'active'` as part of the brIdentity query, which will return not found if an identity exists, but is not active, and the existing handlers will take care of the rest.
2. Do additional checking for the identity status after it is returned from brIdentity, and return an error as appropriate.

**Comment by dlongley** [comment]
I vote option 1.

**Comment by mattcollier** [comment]
Landed: https://github.com/digitalbazaar/bedrock-passport/commit/d8f9e9b3e29cd93af9ca0a16b86d2dbf95bbe084
