### ISSUE TITLE
HttpSignatureStrategy should accept request-line or request-target

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-passport#17]
`request-line` was renamed to `(request-target)` in the [spec](https://tools.ietf.org/html/draft-cavage-http-signatures-06). We should update `HttpSignatureStrategy` to support either until we can remove support for `request-line`.

**Comment by mattcollier** [comment]
Landed https://github.com/digitalbazaar/bedrock-passport/commit/33094af6d3c6873cd52dae312b471ad2e3f9a9ed
