### ISSUE TITLE
Upgrade jsonld-signatures

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-passport#34]
https://github.com/digitalbazaar/bedrock-passport/blob/f53dfe736678eeb4d45ec7679e1a37ecd2680040/lib/httpSignatureStrategy.js#L11-L12

@dlongley given all the recent work in http-signatures, do we want to keep this stuff basically the way it is, or do you see some new/better implementation possibilities?

My interest is eliminating native dependencies, and the jsonld-signatures@2 here has a chloride dep.  I'm looking to get this working with https://github.com/digitalbazaar/jsonld-signatures/tree/node-12

**Comment by dlongley** [comment]
We want to remove http signature support from bedrock-passport and stop using it all together. We probably only care about session support via passport -- everything else should be removed and we should cut a new version.

**Comment by dlongley** [comment]
This has been removed, closing.
