### ISSUE TITLE
req.login is not a function

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-passport#45]
`req.login` is a function that [`passport`](https://www.npmjs.com/package/passport) adds to node's `Request`/`IncomingHTTPMessage` object. It is possible to hit [this route in `bedrock-authn-token-http`](https://github.com/digitalbazaar/bedrock-authn-token-http/blob/f46d77eec83f95c892c586bd0a4f704893434f5e/lib/index.js#L204-L244) and `req.login` is not set on the node `Request` object.  This results in the following error:

```js
2021-09-22T14:30:20.524Z - error: [express] error workerPid=39514, workerId=69404ac87fe2bea0, details={
  "error": {
    "message": "An error occurred.",
    "type": "Error",
    "details": null,
    "cause": {
      "message": "req.login is not a function",
      "type": "TypeError",
      "details": {
        "inspect": "TypeError: req.login is not a function\n    at project/node_modules/bedrock-authn-token-http/lib/index.js:225:11\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
        "stack": {
          "message": "TypeError: req.login is not a function",
          "at": [
            "/home/liminal18/Programs/nodejs/project/node_modules/bedrock-authn-token-http/lib/index.js:225:11",
            "processTicksAndRejections (internal/process/task_queues.js:95:5)"
          ]
        }
      },
      "cause": null
```

Steps:

1. Go to the login page for your project
2. Fill in the login details
3. Shut the project down
4. Clear redis and mongodb databases for that project
5. Start the project
6. Immediately start to try to login
7. Logins will fail for a variety of reasons (such user not found)
8. If you manage to get the `req.login` is not a function bug you have replicated
9. I logged `req.login` from `bedrock-authn-token-http` and it was `undefined` for me.

[This PR might fix the problem by upgrading to `passport: ^0.5.0`.](https://github.com/digitalbazaar/bedrock-passport/pull/44)

**Comment by dlongley** [comment]
Closing as fixed by #44.
